import Head from "next/head"
import Image from "next/image"
import { useMediaQuery } from "../hooks"
import Grid from "../assets/grid.svg"
import GridSm from "../assets/grid-sm.svg"
import GridLg from "../assets/grid-lg.svg"

import LoginButton from "../components/landing/loginButton"

const Home = () => {
  const mediaLg = useMediaQuery("(min-width: 1024px)")
  const mediaSm = useMediaQuery("(min-width: 640px)")

  return (
    <div>
      <Head>
        <title>Oneway</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative flex h-screen w-screen flex-col items-center justify-center overflow-hidden">
        <div className="absolute h-full w-full">
          {mediaLg ? (
            <div className="grid-gradient relative mt-[60vh] h-[40vh] w-full">
              <Image
                src={GridLg}
                className="pointer-events-none absolute bottom-0 h-full w-full select-none"
                alt=""
                objectFit="cover"
                layout="fill"
              />
            </div>
          ) : mediaSm ? (
            <div className="grid-gradient relative mt-[55vh] h-[45vh] w-full">
              <Image
                src={Grid}
                className="pointer-events-none absolute bottom-0 h-full w-full select-none"
                alt=""
                objectFit="cover"
                layout="fill"
              />
            </div>
          ) : (
            <div className="grid-gradient relative mt-[55vh] h-[45vh] w-full">
              <Image
                src={GridSm}
                className="pointer-events-none absolute bottom-0 h-full w-full select-none"
                alt=""
                objectFit="cover"
                layout="fill"
              />
            </div>
          )}
        </div>

        <LoginButton />
      </main>
    </div>
  )
}

export default Home
