import Head from "next/head"
import { useRouter } from "next/router"
import Link from "next/link"

import { getSession } from "next-auth/react"
import { GetServerSideProps } from "next"

import LoginButton from "../../components/landing/loginButton"

const Home = () => {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>OneWay Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative z-10 flex h-screen w-screen flex-col items-center justify-center overflow-hidden">
        {/* dashboard */}

        <nav className="fixed top-0 w-screen border-b-[1px] border-white/20 bg-black/50 px-16 pt-4 backdrop-blur-md">
          <div className="flex w-full items-center justify-between">
            <Link
              href="/dashboard"
              className="select-none text-2xl font-semibold">
              OneWay
            </Link>

            <LoginButton />
          </div>

          <ul className="mt-2 list-none space-x-3">
            <li
              className={`inline-block ${
                router.pathname == "/dashboard"
                  ? "border-b-[2px] border-white"
                  : ""
              }
                 pb-1 duration-200`}>
              <Link
                href="/dashboard"
                className={`rounded px-2 py-[3px] duration-200 hover:bg-white/[0.15]`}>
                Overview
              </Link>
            </li>
            <li
              className={`inline-block ${
                router.pathname == "/dashboard/create"
                  ? "border-b-[2px] border-white"
                  : ""
              }
                 pb-1 duration-200`}>
              <Link
                href="/dashboard/create"
                className={`rounded px-2 py-[3px] duration-200 hover:bg-white/[0.15]`}>
                Create
              </Link>
            </li>
            <li
              className={`inline-block ${
                router.pathname == "/dashboard/settings"
                  ? "border-b-[2px] border-white"
                  : ""
              }
                 pb-1 duration-200`}>
              <Link
                href="/dashboard/settings"
                className={`rounded px-2 py-[3px] duration-200 hover:bg-white/[0.15]`}>
                Settings
              </Link>
            </li>
          </ul>
        </nav>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    }
  }

  return {
    props: { session },
  }
}

export default Home
